### ISSUE TITLE
check on the tendons limits (finger joints)

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#28]
It is not using rotorPosMin/rotorPosMax parameters as required by the specifications

**Comment by ale-git** [comment]
The cable limit is managed at higer level than motor because the backward (=hand open) limit of the motor is dependant by the finger positions. The motor must not preceed the finger in the opening phase or the cable can jump out of the pulley even for a small angle, thus simple "motor max pos" and "motor_min_pos" are not sufficient.

**Comment by randaz81** [comment]
Obsolete for new R1 hand. Closing.
