### ISSUE TITLE
Test CER michrophones

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#31]
Not implemented yet.

**Comment by barbalberto** [comment]
Low priority

**Comment by barbalberto** [comment]
Spoke with Francesco Diotalevi. The HW configuration of mics is the same as the display. 

The FPGA is in charge of acquiring data from the microphones and made them available to the OS. This  is because later on a beam forming algorithm will (probably) be implemented inside the FPGA.

A custom character driver has been made by Francesco to read the data.

Since it is a character driver, it is not seen by the OS as a sound card, therefore the standard utilities that deals with audio devices cannot be used, neither portaudio.

There are 2 possible ways to go:

1) Create a linux driver for sound card, so that any standard library can work with (like portaudio). More complicated.
2) Create a custom yarp driver reading from character device. Easier, but only yarp SW could use the microphones.

**Comment by lornat75** [comment]
I think we can bring this issue at the next meeting and discuss the priorities. I would be better to implement a proper linux driver, if we have time and resources.

**Comment by randaz81** [comment]
Addressed in https://github.com/hsp-iit/research-development/issues/73
