### ISSUE TITLE
USB camera configuration

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#34]
check all the settings (gain, intensity, saturation etc)
driver can be improved to allow on-the-fly change of resolution.

**Comment by randaz81** [comment]
I think on-the-fly change of resolution is not yet implemented. @barbalberto

**Comment by barbalberto** [comment]
Yes, it has been implemented by @nicogene some months ago actually.
It is already been tested on robot and it works pretty well.
The last piece would be extend the frameGrabberGui to include it but we had no time for it.
Command through RPC are available

Settings (gain, aturatio ...) are working since epoch  :-)
